# Generated by Django 3.0.2 on 2020-06-04 07:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0127_auto_20200604_1024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations_9001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Maintenence schedule')),
            ],
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-04062020739', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.CreateModel(
            name='mod9001_calibration',
            fields=[
                ('calibration_date', models.DateField(verbose_name='Date:')),
                ('calibration_number', models.CharField(default='TEGA-C-04062020174', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:')),
                ('type', models.TextField(blank=True, help_text='Calibration type', null=True, verbose_name='Calibration type:')),
                ('device_id', models.TextField(blank=True, help_text='Device ID', null=True, verbose_name='Device ID:')),
                ('manufacturer', models.TextField(blank=True, help_text='Device Manufacturer', null=True, verbose_name='Manufacturer:')),
                ('range', models.TextField(blank=True, help_text='Range', null=True, verbose_name='Range:')),
                ('date_today', models.DateField(default=datetime.datetime.now, verbose_name='Date created:')),
                ('calibrated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doneby', to='accounts.employees', verbose_name='Done by:')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cal_entered_by', to=settings.AUTH_USER_MODEL)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calstandard', to='operations_9001.document_standard', verbose_name='Standard:')),
            ],
        ),
        migrations.CreateModel(
            name='maintenance',
            fields=[
                ('maintenance_number', models.CharField(default='TEGA-M-04062020896', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:')),
                ('id', models.TextField(blank=True, help_text='Enter ID or Serial #', null=True, verbose_name='ID:')),
                ('manufacturer', models.TextField(blank=True, help_text='Manufacturer', null=True, verbose_name='Manufacturer:')),
                ('date', models.DateField(verbose_name='Manufacture Date:')),
                ('location', models.TextField(blank=True, help_text='Location', null=True, verbose_name='Location:')),
                ('detials', models.TextField(blank=True, help_text='Details', null=True, verbose_name='Details:')),
                ('maintenanceby', models.CharField(choices=[('1', 'Internal technician'), ('2', 'External technician')], max_length=200)),
                ('name', models.TextField(blank=True, help_text='Name', null=True, verbose_name='Name of Techncian:')),
                ('parts', models.TextField(blank=True, help_text='Parts replaced', null=True, verbose_name='Parts replaced:')),
                ('notes', models.TextField(blank=True, help_text='Notes', null=True, verbose_name='Notes:')),
                ('date_today', models.DateField(default=datetime.datetime.now, verbose_name='Date created:')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_entered_by', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipment', to='operations_9001.equipment', verbose_name='Equipment:')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule', to='operations_9001.schedule', verbose_name='Schedule:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.employees', verbose_name='user:')),
            ],
        ),
    ]
