# Generated by Django 3.0.2 on 2020-06-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0005_auto_20200605_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_document_manager',
            name='doc_name',
            field=models.TextField(blank=True, help_text='Document Name', null=True, verbose_name='Document Name:'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-09062020749', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-09062020105', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_id',
            field=models.TextField(blank=True, help_text='Ref No.', null=True, verbose_name='Document ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-09062020435', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='origin',
            field=models.CharField(choices=[('1', 'Internal'), ('2', 'External')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='retention',
            field=models.CharField(choices=[('1', 'Internal'), ('2', 'External')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='status',
            field=models.CharField(choices=[('1', 'Internal'), ('2', 'External')], max_length=200, null=True),
        ),
    ]
