# Generated by Django 3.0.2 on 2020-06-15 10:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0097_auto_20200615_1355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations_9001', '0011_auto_20200612_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Program Description')),
            ],
        ),
        migrations.CreateModel(
            name='qmsstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
            ],
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-1506202014', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-15062020346', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-15062020496', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.CreateModel(
            name='mod9001_qmsplanner',
            fields=[
                ('planner_number', models.CharField(default='Comp-QP-15062020424', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:')),
                ('plan_date', models.DateField(verbose_name='Plan Date:')),
                ('start', models.DateField(verbose_name='Start Date:')),
                ('end', models.DateField(verbose_name='End Date:')),
                ('details', models.TextField(blank=True, help_text='Additional Description', null=True, verbose_name='Additional Description:')),
                ('rejected', models.TextField(blank=True, help_text='If rejected, please give a reason', null=True, verbose_name='Reason for rejecting:')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Date Approved:')),
                ('verification_status', models.CharField(blank=True, max_length=200, null=True)),
                ('verification_failed', models.TextField(blank=True, help_text='If rejected, please give a reason', null=True, verbose_name='Reason for rejecting:')),
                ('due', models.DateField(blank=True, null=True, verbose_name='When:')),
                ('completion', models.DateField(default=datetime.datetime.now, verbose_name='Completion Date:')),
                ('scheduled', models.DateField(default=datetime.datetime.now, verbose_name='Rescheduled Date:')),
                ('date_today', models.DateField(default=datetime.datetime.now, verbose_name='Date created:')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qmsApprov_by', to=settings.AUTH_USER_MODEL)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progdesc', to='operations_9001.prod_description', verbose_name='Program description:')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_entered_by', to=settings.AUTH_USER_MODEL)),
                ('planner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_by', to=settings.AUTH_USER_MODEL)),
                ('qmsstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.qmsstatus', verbose_name='Verification Status:')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.approval_status', verbose_name='Status:')),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.RISK_OPPverification', verbose_name='Verification:')),
            ],
        ),
    ]
