# Generated by Django 3.0.2 on 2020-06-24 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0139_auto_20200624_1415'),
        ('operations_9001', '0013_auto_20200619_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-24062020129', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-24062020532', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-24062020503', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-24062020696', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.CreateModel(
            name='mod9001_trainingregister',
            fields=[
                ('training_number', models.CharField(default='Comp-TR-24062020679', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:')),
                ('nature', models.CharField(choices=[('1', 'Planned'), ('2', 'Not Planned')], max_length=200, null=True)),
                ('training_desc', models.TextField(blank=True, null=True, verbose_name='Training Description:')),
                ('trainingplanid', models.TextField(blank=True, null=True, verbose_name='Training Plan ID:')),
                ('training', models.TextField(blank=True, null=True, verbose_name='Training:')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Location:')),
                ('trainee', models.TextField(blank=True, null=True, verbose_name='Trainee:')),
                ('completion_date', models.DateField(verbose_name='Completion Date:')),
                ('job', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=200, null=True, verbose_name='Employee Job performance level has raised ')),
                ('skills', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=200, null=True, verbose_name='Training skills applied by trainee ')),
                ('indicators', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=200, null=True, verbose_name='Indicators exist that prove the employee benefited from the acquired skills in this Training course')),
                ('able', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=200, null=True, verbose_name='Employee Able to train others')),
                ('decision', models.TextField(blank=True, null=True, verbose_name='Evaluation Decision:')),
                ('tainee_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traineeDepartment', to='accounts.Department', verbose_name='Trainee Department ID:')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
