# Generated by Django 3.0.2 on 2020-07-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0017_auto_20200708_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='train_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Training Description')),
            ],
        ),
        migrations.CreateModel(
            name='train_objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Training Objective')),
            ],
        ),
        migrations.CreateModel(
            name='train_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Training Status')),
            ],
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-14072020779', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-14072020195', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-14072020236', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-14072020305', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-14072020848', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
        migrations.CreateModel(
            name='mod9001_trainingplanner',
            fields=[
                ('plan_number', models.CharField(default='Comp-TP-14072020951', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:')),
                ('trainng_date', models.DateField(null=True, verbose_name='Training Date:')),
                ('type', models.CharField(choices=[('1', 'Planned'), ('2', 'Not Planned')], max_length=200, null=True)),
                ('other', models.TextField(blank=True, null=True, verbose_name='Other training description:')),
                ('trainaudience', models.CharField(choices=[('1', 'Employee'), ('2', 'Other')], max_length=200, null=True)),
                ('other_audience', models.TextField(blank=True, null=True, verbose_name='Other Training Audience:')),
                ('start', models.DateField(verbose_name='Start Date:')),
                ('end', models.DateField(verbose_name='End Date:')),
                ('trainlocation', models.CharField(choices=[('1', 'Company Premise'), ('2', 'Other')], max_length=200, null=True)),
                ('other_location', models.TextField(blank=True, null=True, verbose_name='Other Location:')),
                ('trainer', models.TextField(blank=True, null=True, verbose_name='Trainer:')),
                ('resources', models.TextField(blank=True, null=True, verbose_name='Resource:')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_desc', to='operations_9001.train_desc')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_objective', to='operations_9001.train_objective')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_status', to='operations_9001.train_status')),
            ],
        ),
    ]
