# Generated by Django 3.0.2 on 2020-08-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0021_auto_20200806_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_description',
            name='incident_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incidentype', to='operations_9001.incident_type', verbose_name='Incident Type:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident_description',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Incident Description'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-06082020150', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-06082020247', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-06082020289', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.RemoveField(
            model_name='mod9001_incidentregister',
            name='incident_description',
        ),
        migrations.AddField(
            model_name='mod9001_incidentregister',
            name='incident_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desc', to='operations_9001.incident_description', verbose_name='Incident Description:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-06082020157', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-06082020292', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-06082020241', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-06082020175', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
