# Generated by Django 3.0.2 on 2020-07-15 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0109_auto_20200715_1117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations_9001', '0023_auto_20200715_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_trainingplanner',
            name='approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Approved:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingplanner',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainplannerApprov_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mod9001_trainingplanner',
            name='due',
            field=models.DateField(blank=True, null=True, verbose_name='When:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingplanner',
            name='rejected',
            field=models.TextField(blank=True, help_text='If rejected, please give a reason', null=True, verbose_name='Reason for rejecting:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingplanner',
            name='train_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_status', to='operations_9001.train_status'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingplanner',
            name='trainplannerstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingplanner',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.RISK_OPPverification', verbose_name='Verification:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingplanner',
            name='verification_failed',
            field=models.TextField(blank=True, help_text='If rejected, please give a reason', null=True, verbose_name='Reason for rejecting:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingplanner',
            name='verification_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-15072020149', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-1507202079', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-15072020401', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-15072020529', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-15072020859', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-150720203', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
