# Generated by Django 3.0.2 on 2020-08-27 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0029_auto_20200825_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='rank',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Final Ranking:'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-27082020272', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-27082020293', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-27082020101', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-27082020121', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='Communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communicatin', to='operations_9001.providerparameters', verbose_name='8. Communication Skills Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='adaptability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptabilit', to='operations_9001.providerparameters', verbose_name='2.\tAdaptability & Flexibility Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilit', to='operations_9001.providerparameters', verbose_name='10.\tAvailability Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-27082020101', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='initiativeness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative', to='operations_9001.providerparameters', verbose_name='4.\tInitiativeness & Resourcefulness Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='jobknowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobknowledg', to='operations_9001.providerparameters', verbose_name='1. Job Knowledge Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plannin', to='operations_9001.providerparameters', verbose_name='5. Planning & Organisation Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='problemsolve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemsolve', to='operations_9001.providerparameters', verbose_name='3.\tProblem Solving Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='professionalism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professionalis', to='operations_9001.providerparameters', verbose_name='11. Professional Contribution Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='operations_9001.providerparameters', verbose_name='7.\tInterpersonal Skills Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='supervision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisio', to='operations_9001.providerparameters', verbose_name='9. Supervision & Management Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemsolv', to='operations_9001.providerparameters', verbose_name='6.\tWork Quality & Quantity Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-27082020220', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-27082020267', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-27082020239', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
