# Generated by Django 3.0.2 on 2020-04-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0003_auto_20200410_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mod9001_issues',
            old_name='added_by',
            new_name='entered_by',
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP_Q-1004202030', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='external_issues',
            field=models.CharField(choices=[('1', 'Organisational Culture'), ('2', 'Organisational Knowledge'), ('3', 'Company Values'), ('4', 'ICT Infrastructure'), ('5', 'Available Resources'), ('6', 'Organisational Structure'), ('7', 'Strength'), ('8', 'Weaknesses')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='internal_issues',
            field=models.CharField(choices=[('1', 'Organisational Culture'), ('2', 'Organisational Knowledge'), ('3', 'Company Values'), ('4', 'ICT Infrastructure'), ('5', 'Available Resources'), ('6', 'Organisational Structure'), ('7', 'Strength'), ('8', 'Weaknesses')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT_Q-10042020293', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP_LRO_Q-10042020226', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
    ]
