# Generated by Django 3.0.2 on 2020-04-10 11:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues_9001', '0004_auto_20200410_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_interestedparties',
            name='companyinterestedparties',
            field=models.CharField(choices=[('1', 'Control'), ('2', 'Influence'), ('3', 'Influence and Control')], default='Control', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_interestedparties',
            name='date_today',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date created:'),
        ),
        migrations.AddField(
            model_name='mod9001_interestedparties',
            name='due',
            field=models.DateField(default='2020-04-10', verbose_name='When:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_interestedparties',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mod9001_interestedparties',
            name='quality_needs',
            field=models.CharField(choices=[('1', 'Communication'), ('2', 'Reporting'), ('3', 'Tax complaince'), ('4', 'CSR'), ('5', 'Time payment for services/products'), ('6', 'Timely delivery'), ('7', 'Safe work enviroment'), ('8', 'Operation support'), ('9', 'Work equipment'), ('10', 'Training'), ('11', 'Clear vision'), ('12', 'Quality support'), ('13', 'Performance feedback'), ('14', 'Contractual complaince'), ('15', 'legal complaince'), ('16', 'Business growth'), ('17', 'Performance')], default='10/04/2020', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='actiontaken',
            field=models.CharField(choices=[('1', 'Training and awareness'), ('2', 'Customer satisfaction survey'), ('3', 'Performance monitoring'), ('4', 'Service Level Management'), ('5', 'Tax Compliance/Policing'), ('6', 'Auditing'), ('7', 'Contract management'), ('8', 'Compliance reviews')], max_length=200, verbose_name='Action to Manage IP:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='internal_issues',
            field=models.CharField(choices=[('1', 'Employee/Staff'), ('2', 'Executive Management'), ('3', 'Top Management')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP_Q-10042020930', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT_Q-1004202016', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP_LRO_Q-10042020538', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
    ]
