# Generated by Django 3.0.2 on 2020-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0005_auto_20200410_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='due',
            field=models.DateField(null=True, verbose_name='When:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP_Q-10042020169', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT_Q-10042020493', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP_LRO_Q-10042020239', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
    ]
