# Generated by Django 3.0.2 on 2020-04-10 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues_9001', '0006_auto_20200410_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_interestedparties',
            name='responsibility',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='IPresponsibility', to=settings.AUTH_USER_MODEL, verbose_name='Responsibility:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP_Q-10042020198', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT_Q-1004202059', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP_LRO_Q-10042020454', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
    ]
