# Generated by Django 3.0.2 on 2020-04-12 08:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues_9001', '0007_auto_20200410_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod9001_regulatoryreq',
            name='deadline',
        ),
        migrations.AddField(
            model_name='mod9001_regulatoryreq',
            name='date_today',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date created:'),
        ),
        migrations.AddField(
            model_name='mod9001_regulatoryreq',
            name='due',
            field=models.DateField(null=True, verbose_name='When:'),
        ),
        migrations.AddField(
            model_name='mod9001_regulatoryreq',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatoryreq_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP_Q-12042020828', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT_Q-1204202026', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP_LRO_Q-12042020882', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='responsibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatoryresponsibility', to=settings.AUTH_USER_MODEL, verbose_name='Responsibility:'),
        ),
    ]
