# Generated by Django 3.0.2 on 2020-04-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0008_auto_20200412_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='contextdetails',
            fields=[
                ('context_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Risk Context ID:')),
                ('cont_desc', models.TextField(verbose_name='Description:')),
            ],
        ),
        migrations.CreateModel(
            name='risklikelihood',
            fields=[
                ('likelihood_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Risk likelihood ID:')),
                ('likelihood_desc', models.TextField(verbose_name='Description:')),
            ],
        ),
        migrations.CreateModel(
            name='riskseverity',
            fields=[
                ('riskseverity_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Risk Severity ID:')),
                ('riskseverity_desc', models.TextField(verbose_name='Description:')),
            ],
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP_Q-15042020477', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT_Q-15042020805', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP_LRO_Q-15042020593', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
    ]
