# Generated by Django 3.0.2 on 2020-04-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0010_auto_20200415_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_risks',
            name='issue_number',
            field=models.ForeignKey(default='TEGA-CT_Q-08042020289', on_delete=django.db.models.deletion.CASCADE, to='issues_9001.mod9001_issues', verbose_name='Issue number:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP_Q-15042020128', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT_Q-15042020978', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP_LRO_Q-15042020519', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-1504202076', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
    ]
