# Generated by Django 3.0.2 on 2020-04-17 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues_9001', '0011_auto_20200415_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mod9001_risks',
            old_name='upload',
            new_name='document',
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP_Q-17042020345', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT_Q-1704202059', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP_LRO_Q-17042020862', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuenumber', to=settings.AUTH_USER_MODEL, verbose_name='Lead Assessor:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-17042020525', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
    ]
