# Generated by Django 3.0.2 on 2020-05-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0023_auto_20200503_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='external_issues',
            field=models.CharField(blank=True, choices=[('1', 'Customers'), ('2', 'Regulators'), ('3', 'Hardware/Equipment Suppliers'), ('4', 'Traning providers'), ('5', 'Security providers'), ('6', 'Internet providers'), ('7', 'Insurance providers'), ('8', 'Auditors'), ('9', 'Certification bodies'), ('10', 'Inspectors'), ('11', 'Business partners'), ('12', 'Competitors'), ('13', 'Neighbourhood'), ('14', 'Local authorities'), ('15', 'Family')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='internal_issues',
            field=models.CharField(blank=True, choices=[('1', 'Employee/Staff'), ('2', 'Executive Management'), ('3', 'Top Management')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP_Q-03052020698', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT_Q-03052020397', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP_LRO_Q-03052020194', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-03052020935', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
    ]
