# Generated by Django 3.0.2 on 2020-05-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0024_auto_20200503_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP_Q-03052020547', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='external_issues',
            field=models.CharField(blank=True, choices=[('1', 'Organisational Culture'), ('2', 'Organisational Knowledge'), ('3', 'Company Values'), ('4', 'ICT Infrastructure'), ('5', 'Available Resources'), ('6', 'Organisational Structure'), ('7', 'Strength'), ('8', 'Weaknesses')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='internal_issues',
            field=models.CharField(blank=True, choices=[('1', 'Organisational Culture'), ('2', 'Organisational Knowledge'), ('3', 'Company Values'), ('4', 'ICT Infrastructure'), ('5', 'Available Resources'), ('6', 'Organisational Structure'), ('7', 'Strength'), ('8', 'Weaknesses')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT_Q-03052020558', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP_LRO_Q-03052020287', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-03052020588', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
    ]
