# Generated by Django 3.0.2 on 2020-09-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0030_auto_20200827_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_issues',
            name='process_desc',
            field=models.CharField(blank=True, choices=[('1', 'HR'), ('2', 'Operations')], max_length=200, null=True, verbose_name='Process Description'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP-Q-06092020757', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT-Q-0609202021', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP-LRO-Q-0609202076', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-06092020855', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
    ]
