# Generated by Django 3.0.2 on 2020-05-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0035_auto_20200508_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_risks',
            name='record_type',
            field=models.TextField(blank=True, help_text='Specifies whether the record is risk or opprotunity entry', null=True, verbose_name='Record Type:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP_Q-08052020734', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT_Q-08052020819', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP_LRO_Q-08052020479', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-08052020771', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
    ]
