# Generated by Django 3.0.2 on 2020-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0039_auto_20200510_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP-Q-10052020885', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='external_issues',
            field=models.CharField(blank=True, choices=[('1', 'Legal and Regulatory requirements'), ('2', 'Economic enviroment'), ('3', 'Cultural enviroment'), ('4', 'Political enviroment'), ('5', 'Competitive enviroment'), ('6', 'Social enviroment'), ('7', 'Threats'), ('8', 'Opportunities')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT-Q-1005202010', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP-LRO_Q-10052020696', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-10052020661', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
    ]
