# Generated by Django 3.0.2 on 2020-05-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_auto_20200513_2123'),
        ('issues_9001', '0045_auto_20200513_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employees', verbose_name='Lead Analyst:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP-Q-13052020912', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT-Q-13052020978', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP-LRO-Q-13052020207', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-13052020666', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
    ]
