# Generated by Django 3.0.2 on 2020-05-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0056_auto_20200515_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_risks',
            name='retainreason',
            field=models.TextField(blank=True, null=True, verbose_name='You chose retain, please give reason:'),
        ),
        migrations.AddField(
            model_name='mod9001_risks',
            name='risktreatment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='risktreatment', to='issues_9001.risktreat', verbose_name='Risk Treatment:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP-Q-15052020346', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT-Q-15052020373', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP-LRO-Q-15052020429', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-15052020306', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
    ]
