# Generated by Django 3.0.2 on 2020-05-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0002_auto_20200516_2216'),
        ('issues_9001', '0058_auto_20200516_0006'),
    ]

    operations = [
    ]
