# Generated by Django 3.0.2 on 2020-05-16 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0061_auto_20200516_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_risks',
            name='likelihood_residue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='likelihood_residue', to='issues_9001.risklikelihood', verbose_name='Risk likelihood:'),
        ),
        migrations.AddField(
            model_name='mod9001_risks',
            name='riskrank_residue',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Risk category:'),
        ),
        migrations.AddField(
            model_name='mod9001_risks',
            name='riskrating_residue',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Risk Rating:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_risks',
            name='severity_residue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='severity_residue', to='issues_9001.riskseverity', verbose_name='Risk Severity:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP-Q-17052020950', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT-Q-17052020840', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP-LRO-Q-17052020181', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-1705202069', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
    ]
