# Generated by Django 3.0.2 on 2020-05-21 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0074_auto_20200519_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_risks',
            name='ip_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.mod9001_interestedParties', verbose_name='IP number:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP-Q-21052020572', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT-Q-21052020707', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP-LRO-Q-21052020772', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='contextdetails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contextdetail', to='issues_9001.contextdetails', verbose_name='Context:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='issue_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.mod9001_issues', verbose_name='Issue number:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-21052020747', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
    ]
