# Generated by Django 3.0.2 on 2020-05-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0078_auto_20200525_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='external_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='External Issue description')),
            ],
        ),
        migrations.CreateModel(
            name='internal_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal Issue description')),
            ],
        ),
        migrations.CreateModel(
            name='process_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Process Issue description')),
            ],
        ),
        migrations.AddField(
            model_name='mod9001_issues',
            name='process_issues',
            field=models.CharField(blank=True, choices=[('1', 'Strength'), ('2', 'Weaknesses'), ('3', 'Opportunities'), ('4', 'Threats')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP-Q-25052020130', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT-Q-25052020234', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP-LRO-Q-25052020351', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-25052020768', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
        migrations.AddField(
            model_name='mod9001_issues',
            name='external_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externaldesc', to='issues_9001.external_description', verbose_name='External Issue description:'),
        ),
        migrations.AddField(
            model_name='mod9001_issues',
            name='internal_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internaldesc', to='issues_9001.internal_description', verbose_name='Internal Issue description:'),
        ),
        migrations.AddField(
            model_name='mod9001_issues',
            name='process_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processdesc', to='issues_9001.process_description', verbose_name='Process Issue description:'),
        ),
    ]
