# Generated by Django 3.0.2 on 2020-01-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='customer',
        ),
    ]
