# Generated by Django 3.0.2 on 2020-01-27 08:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20200123_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Department ID:')),
                ('dept_name', models.TextField(verbose_name='Name:')),
            ],
        ),
        migrations.CreateModel(
            name='NonConformityAction',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Non conformity ID.:')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Containment action')),
            ],
        ),
        migrations.CreateModel(
            name='NonConformitySource',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Non conformity ID.:')),
                ('description', models.CharField(max_length=200, verbose_name='Non Conformity')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
        migrations.CreateModel(
            name='NonConformityList',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Non conformity ID.:')),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.NonConformitySource', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('car_no', models.CharField(default='270120202199', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:')),
                ('car_dateoccur', models.DateField(default=datetime.datetime.now, verbose_name='Date of Occurence:')),
                ('car_time', models.TimeField(default=datetime.datetime.now, verbose_name='Time:')),
                ('car_issue', models.TextField(blank=True, null=True, verbose_name='Non conformity/Issue:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Describe:')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Containment action')),
                ('car_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department', verbose_name='Affected Department ID:')),
                ('car_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reported by:')),
                ('nonconf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.NonConformitySource')),
            ],
        ),
    ]
