# Generated by Django 3.0.2 on 2020-01-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200127_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonconformitylist',
            name='description',
        ),
        migrations.AddField(
            model_name='nonconformitylist',
            name='Description',
            field=models.CharField(default='Other', max_length=100, verbose_name='Description.:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonconformitylist',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.NonConformitySource', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_no',
            field=models.CharField(default='270120202215', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='nonconformitylist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
