# Generated by Django 3.0.2 on 2020-03-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20200310_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='verification_failed',
            field=models.TextField(blank=True, help_text='If rejected, please give a reason', null=True, verbose_name='Reason for rejecting:'),
        ),
        migrations.AddField(
            model_name='car',
            name='verification_status',
            field=models.CharField(choices=[('Closed', 'Close'), ('Rejected', 'Reject')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='TEGA10032020234', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Carstatus', verbose_name='CAR status:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
