# Generated by Django 3.0.2 on 2020-05-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_auto_20200511_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='TEGA13052020564', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Carstatus', verbose_name='CAR status:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('employeeID', models.CharField(default='TEGA420', max_length=10, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('registered', models.DateField(verbose_name='Reg. Date:')),
                ('firstName', models.TextField(blank=True, verbose_name='First Name')),
                ('lastName', models.TextField(verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='accounts.Department', verbose_name='Department:')),
            ],
        ),
    ]
