# Generated by Django 3.0.2 on 2020-05-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200516_2216'),
        ('accounts', '0098_auto_20200516_0006'),
    ]

    operations = [
    ]
